### PR TITLE
fix(ep-phone-number): [CR-1195] Display flags in EpPhoneNumber

### PR DESCRIPTION
**Pull request by antonioliv**
Fix a bug where the flag images don't show

Refs: https://www.loom.com/share/2ee28d0a95f94ceda41ba53d40a28d56

### CODE REVIEW

**Comment by antonioliv** [comment]
This is a tricky case.

Problems: The flags are not showing and it is caused by either:

-  No/Wrong rollup configuration for url images
- Bug on source code of the component

Solutions:

- adding @rollup/plugin-url and manage the configuration
- adding flags image to the project and override de css with ::v-deep (monkey way)

**Comment by antonioliv** [comment]
After almost 2 days on this bug, I could not find a way to fix the problem in a more concise, professional and reliable way, if we can call that. So I applied the second point solution, which adds the image, encoded as base64, to the css of the wrapper component - `EpPhoneNumber`.

I've tried to look for the source code of the `vue-phone-number-input`, not too deep, but didn't find any information about the building process that could solve this.

Since we use rollup I went looking in the author library - `LouisMazel/maz-ui` - for more information and this caught my eyes -> https://github.com/LouisMazel/maz-ui/blob/next/packages/lib/package/components/MazPhoneNumberInput/css/flags.css 

The author used the same approach, the base64 encoded image. So, my conclusion is that something on the versioning of the plugins/dependencies could be interfering with the building configuration. Major releases, rollup, postcss, loaders or even the configuration itself can be overwhelmed by too many plugins not resulting in a proper output.

In the future this should be addressed on a major dependencies update release.

**Comment by antonioliv** [comment]
https://www.loom.com/share/3e36763d53144ad09629e2639bf1d2e7

**Review by Arlanthir — APPROVED** [review]
LGTM

**Comment by antonioliv** [comment]
For further development with exported ui-library images, see this https://www.npmjs.com/package/@nuxtjs/svg

**Pull request merged**
